Name: Roles
Id: g=168315c4ba704e70bb13e35de715eb03
Type: RolesCategoryFolder
Children:
- Name: admin
  Id: g=9b9c964b82ffd32df20685ed526b6e4a
  Type: ns=1;RoleType
  DisplayName: {"NamespaceIndex":36,"TextId":"Administrator"}
- Name: jones
  Id: g=eeb625bfbd66a7c72514c879fa201b2f
  Type: ns=1;RoleType
  DisplayName: {"NamespaceIndex":36,"TextId":"Jones"}
- Name: maintenance
  Id: g=cfd5c78595304bf3c8a351b3de4eedba
  Type: ns=1;RoleType
  DisplayName: {"NamespaceIndex":36,"TextId":"Maintenance"}
- Name: operator
  Id: g=2a6734f56d95341c0016f564b164feee
  Type: ns=1;RoleType
  DisplayName: {"NamespaceIndex":36,"TextId":"Operator"}
