Name: Production Time
Type: FolderType
Children:
- Name: AlarmTime
  Type: BaseDataVariableType
  DataType: Int32
  Value: 9735
- Name: OperatorTime
  Type: BaseDataVariableType
  DataType: Int32
  Value: 4572
- Name: RunTime
  Type: BaseDataVariableType
  DataType: Int32
  Value: 28523
- Name: OutsideStopTime
  Type: BaseDataVariableType
  DataType: Int32
  Value: 6564
