Name: Production Data
Type: FolderType
Children:
- Name: Shift Cartons Fed
  Type: BaseDataVariableType
  DataType: Int32
  Value: 52635
- Name: Shift Cartons Produced
  Type: BaseDataVariableType
  DataType: Int32
  Value: 61435
- Name: Shift Cartons Rejected
  Type: BaseDataVariableType
  DataType: Int32
  Value: 4513
- Name: Total Cartons Fed
  Type: BaseDataVariableType
  DataType: Int32
  Value: 4156143
- Name: Total Cartons Produced
  Type: BaseDataVariableType
  DataType: Int32
  Value: 4153643
- Name: Total Cartons Rejected
  Type: BaseDataVariableType
  DataType: Int32
  Value: 47525
- Name: RejectArray
  Type: BaseDataVariableType
  DataType: Int32
  ValueRank: OneDimension
  ArrayDimensions: [12]
  Value: [75,71,52,83,28,47,39,37,28,52,26,92]
