Name: Production Statistics Charts
Id: g=df17ef34904dd2847df3abbe304d32fb
Type: FolderType
Children:
- File: Inner_Ring_(Good_Items)/Inner_Ring_(Good_Items).yaml
- File: Outer_Ring_(Bad_Items)/Outer_Ring_(Bad_Items).yaml
