Name: Production Statistics Charts
Id: g=c022829e3ca6749de23efd14a5659075
Type: FolderType
Children:
- File: Inner_Ring_(Good_Items)/Inner_Ring_(Good_Items).yaml
- File: Outer_Ring_(Bad_Items)/Outer_Ring_(Bad_Items).yaml
